name: PrimeEC
version: '1.0.0'
main: com.primesmp.ec.PrimeEC
api-version: '1.20'
author: PrimeSMP
description: Open your ender chest from anywhere with /ec

commands:
  enderchest:
    aliases: [ec]
    description: Open your ender chest
    usage: /<command> [player]

permissions:
  primeec.use:
    description: Allows opening your own ender chest with /ec
    default: true
  primeec.others:
    description: Allows viewing/editing other players' ender chests
    default: op
